// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rlryalfavicegywitrxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJscnlhbGZhdmljZWd5d2l0cnh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTM0ODQ5NjEsImV4cCI6MjA2OTA2MDk2MX0.8Pl3op23jlH2x5qNrw2oHiRc8ssY__GLl9TOg41TNU0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});