// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://sbwnqwgubyjlznihzmqc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InNid25xd2d1YnlqbHpuaWh6bXFjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTI4NjI5ODMsImV4cCI6MjA2ODQzODk4M30.7dCPPMpGQcZ0dmWxq_mlOwHS5bWZ7Z4bSJxTPOCT_Ts";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});